[package]
name = "strand_match"
version = "0.1.0"
authors = ["ComplexPlane <comlexplanegames@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strsim = "0.9.2"
#quick-xml = "0.17.0"
hex = "0.4.0"
roxmltree = "0.7.1"
